### ISSUE TITLE
Voicemeeter banana connection problems

### ISSUE THREAD

**Issue by micah45162** [mozzieongit/VoiceMeeter-Unified-Remote-Controller#1]
This is not really a "issues" but I can't get it to connect to my PC so I can do it wirelessly 

I did all the steps the way you are supposed to get working

What service client did you use in the app "unified remote full"

Because I have tried " custom scripts " and " custom keys "but I can't get it to work, can you help me get to work

**Comment by mozzieongit** [comment]
Hi, 
what do you mean with "what service client"?

Did you successfully connect Unified Remote to your system?

**Comment by ka0sdev** [comment]
NIcely done, however I am also facing issues getting the connection between Unified Remote and VoiceMeeter, I have successfully added the remote, and the lua is loaded, but on Strip 1 I am seeing: 
![image](https://user-images.githubusercontent.com/16397298/80570775-ac602480-89fb-11ea-8c6a-7c7c356283ab.png)

Any advise?

**Comment by mozzieongit** [comment]
It seems like Unified Remote isn't able to find the VoicemeeterRemote Controller Application (the tray program started by the .exe file). I don't have any clue why though. I'd need to test it. I haven't used that program for a while.
Probably dump question: did you start the exe file?

Edit:
I should add the automatic start of that application to the lua code.
